version: "3.9"
services:
  kdbx-headless:
    build: .
    command:
      - "--ssl"
      - "/etc/kdbx-headless/ssl"
      - "--bind"
      - "0.0.0.0"
    environment:
      DBUS_SESSION_BUS_ADDRESS: ${DBUS_SESSION_BUS_ADDRESS}
      UID: ${UID}  # UID/GID are shell variables must be exported first
      GID: ${GID}
    restart: unless-stopped
    network_mode: host
    user: "$UID:$GID" # override with $(id -u):$(id -g)
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /run/user/$UID/bus
        target: /run/user/$UID/bus
        read_only: true
      - type: bind
        source: /var/run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
        read_only: true
      - type: volume
        source: kdbx
        target: /etc/kdbx
        read_only: true
      - type: volume
        source: kdbx-headless
        target: /etc/kdbx-headless
        read_only: true
volumes:
  kdbx-headless:
    driver: local
    driver_opts:
      o: bind
      type: none
#      device:
  kdbx:
    driver: local
    driver_opts:
      o: bind
      type: none
#      device: