version: "3.9"
services:
  kdbx-headless:
    build: .
    environment:
      DBUS_SESSION_BUS_ADDRESS: ${DBUS_SESSION_BUS_ADDRESS}
    restart: unless-stopped
    network_mode: host
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: /run/user/1000/bus
        target: /run/user/1000/bus
        read_only: true
      - type: bind
        source: /var/run/dbus/system_bus_socket
        target: /var/run/dbus/system_bus_socket
        read_only: true
      - type: volume
        source: kdbx
        target: /etc/kdbx
        read_only: true
      - type: volume
        source: kdbx-headless
        target: /etc/kdbx-headless
        read_only: true
volumes:
  kdbx-headless: {}
  kdbx: {}
